<? $this->headTitle($this->page->title); ?>

<? if ($this->page->getParam('show_title')): ?>
<table class="contentpaneopen">
    <tr>
        <td class="contentheading">
            <?= $this->escape($this->page->title); ?>
        </td>
    </tr>
</table>
<? endif; ?>

<? if ($this->page->getParam('show_cdate')): ?>
<div class="createdate">
    <?= $this->page->getCdate(); ?>
</div>
<? endif; ?>

<div class="contentpaneopen">
<?= $this->page->content; ?>
</div>

<? if ($this->page->getParam('show_mdate')): ?>
<div class="modifydate">
    Last Updated ( <?= $this->page->getMdate(); ?> )
</div>
<span class="article_separator"></span>
<? endif; ?>